#!/bin/bash

set -eu
set -o pipefail

KGG=kgg
KGG_ARGS=""
while (( ${#*} > 0 )); do
    case $1 in
        -c)
            KGG=kggc
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            KGG_ARGS="$KGG_ARGS$1 "
            shift
            ;;
    esac
done

k exec -ti $($KGG $KGG_ARGS) -- env COLUMNS=$COLUMNS LINES=$LINES TERM=$TERM ${@:-/bin/sh -c '(test -f /bin/bash && /bin/bash) || /bin/sh'}
