#!/bin/bash

set -eu
set -o pipefail

KGG_ARGS=""
while (( ${#*} > 0 )); do
    case $1 in
        *)
            KGG_ARGS="$KGG_ARGS$1 "
            shift
            ;;
        --)
            break
            ;;
    esac
done

k exec -ti $(kggc $KGG_ARGS) "${@:-/bin/sh}"
