#!/bin/bash

set -eu
set -o pipefail

help() {
    cat <<EOT
Gets the full name of pods filtered by a pattern or interactively picked.

kgg -h|--help
    This help
kgg [-g|--grep] pattern ...
    Only include results matching <pattern>.
    If multiple patterns are given, all must match.
kgg -i|--ignore pattern ...
    Exclude results matching <pattern>.
kgg -p|--percol ...
    Interactively filter the resources with Percol.
kgg -k|--kind kind ...
    Search for something other than pods.
EOT
}

PASS=()
KIND="po"
while (( ${#*} > 0 )); do
    case $1 in
        -h|--help)
            help
            exit
            ;;
        -k|--kind)
            shift
            KIND="$1"
            shift
            ;;
        *)
            PASS+=("$1")
            shift
            ;;
    esac
done

k get $KIND | pick --skip-header-line "${PASS[@]}"
