#!/bin/bash

set -eu
set -o pipefail

help() {
    cat <<EOT
Gets the full name of pods filtered by a pattern or interactively picked.

kgg [-h|--help]
    This help
kgg [-g|--grep] pattern ...
    Only include results matching <pattern>.
    A single pattern can be given as a positional parameter.
    If multiple patterns are given, all must match.
kgg [-i|--ignore] pattern ...
    Exclude results matching <pattern>.
kgg [-p|--percol] ...
    Interactively filter the resources with Percol.
kgg [-k|--kind] kind ...
    Search for something other than pods.
EOT
}

INCLUDE=""
EXCLUDE=""
PERCOL=""
KIND="po"
while (( ${#*} > 0 )); do
    case $1 in
        -h|--help)
            help
            exit
            ;;
        -g|--grep)
            shift
            INCLUDE="$INCLUDE|$1"
            shift
            ;;
        -i|--ignore)
            shift
            EXCLUDE="$EXCLUDE|$1"
            shift
            ;;
        -p|--percol)
            shift
            PERCOL=1
            ;;
        -k|--kind)
            shift
            KIND="$1"
            shift
            ;;
        *)
            if [[ -z "$INCLUDE" ]]; then
                INCLUDE="$INCLUDE|$1"
                shift
            else
                echo "Unrecognised argument: $1"
                exit
            fi
            ;;
    esac
done
INCLUDE="${INCLUDE#|}"
EXCLUDE="${EXCLUDE#|}"

AWKCMD="NR>1 ${INCLUDE:+&& /$INCLUDE/} ${EXCLUDE:+&& !/$EXCLUDE/} { print \\\$1 }"
CMD="k get $KIND | awk \"$AWKCMD\"" # | tr '\n' ' '"
if [[ -n "$PERCOL" ]]; then
    CMD="$CMD | percol"
fi
eval $CMD
