#!/bin/bash

set -eu
set -o pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export KUBE_EDITOR="$DIR/kube-secret-editor.py"

if (( ${#*} > 0 )); then
    k edit secret $(kgg secret "$@")
else
    k edit secret "$@"
fi
