kubectl-fns
===========

kubectl convenience functions. Add `. <path>/{bash,zsh}rc` to your shell rc and
export KUBE_NS='your-kubectl-namespace'.

Dependencies: kubectl, percol

`kswitch` will ask kubectl what namespaces are available and lets you set one
as KUBE_NS.

`k` is the kubectl replacement. It sets `-n $KUBE_NS` and adds a few command
aliases.

`col N` uses awk to return column N, default 1. `col skip N` drops the first
line.

`kgg` (k get grep) takes a kind and regex. It `get`s the kind, greps by the
regex and returns the first column, usually the full name of the thing matching
the regex.

`kgp` is like `kgg` but instead of taking a regex, it asks you to pick via
percol.

`kre` is like `k`, but uses `kgg`. Useful to abbreviate EG pod names: `kre desc
po comm`.

`kex` will try to find a pod matching the given regex and open a shell there,
or you can specify a command. `--` is already included, don't add it again.

`ksql` is basically `kex postgres psql`.

`ksetsecret` uses `kube-secret-editor.py` to set values from `~/.ksecretvals`
into the given secret (via `kgg`). EG if your secret (`root-pg-password`) looks
like:

    junk...
    data:
      foo: b64-encode(wabbadoo)
      bar: b64-encode(yoink)
    other junk...

then you can set `bar` by having `~/.ksecretvals`:

    bar: yeet

And running:

    ksetsecret pg

The Python is maintained at https://github.com/lxsli/kube-secret-editor, please
push edits there first. It requires Python3 and PyYAML.
